version: '3.4'
services:

  install:
    build:
      context: ./
      dockerfile: docker/dependencies/Dockerfile
    volumes:
    - ./tmp:/home/app/projects

  test:
    image: lambci/lambda:python3.6
    volumes:
    - ./tmp:/var/task
    command: $LAMBDA_MODULE $TEST_EVENT

  build:
    build:
      context: ./
      dockerfile: docker/deploy/Dockerfile
    volumes:
    - ./tmp:/var/task
    container_name: $LAMBDA_MODULE
    environment:
    - AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID
    - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - AWS_REGION=$AWS_REGION
    - EXE_MODULE=$LAMBDA_MODULE
    - FUNCTION_NAME=$LAMBDA_FUNCTION_NAME
